name: dev
channels:
  - defaults
dependencies:
  - python=3.11
  - dask
  - flake8
  - ipykernel
  - ipympl
  - ipywidgets
  - jax
  - joblib
  - jupyterlab
  - lightgbm
  - matplotlib
  - mypy
  - networkx
  - nodejs
  - numba::numba
  - numpy
  - pandas
  - pip
  - plotly
  - pre-commit
  - psutil
  - pylint
  - pytest
  - pytest-cov
  - pytorch::cpuonly
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - pytz
  - requests
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - shap
  - statsmodels
  - tqdm
  - xgboost
  - yarn
  - pip:
    - TA-Lib
    - alphalens-reloaded
    - aquirdturtle_collapsible_headings
    - backtrader
    - bidask
    - black[jupyter]
    - corr-shap
    - cvxpy
    - darts
    - dask-labextension
    - empyrical-reloaded
    - isort
    - jupyter-server-proxy
    - jupyterlab-drawio
    - jupyterlab-execute-time
    - jupyterlab_vim
    - lckr-jupyterlab-variableinspector
    - ml_insights
    - mlflow
    - mlforecast
    - nbqa
    - neuralforecast
    - openbb
    - optuna
    - pandas-datareader
    - pandas_market_calendars
    - pandas_ta
    - polars
    - pyfolio-reloaded
    - pynvim
    - pysabr
    - pyvinecopulib
    - quantstats
    - riskfolio-lib
    - ruff
    - seaborn
    - statsforecast
    - web3
    - zipline-reloaded
