name: dev
channels:
  - defaults
dependencies:
  - python=3.12
  - alembic
  - dask>=2023.1.0
  - flake8
  - ipykernel
  - ipympl
  - ipywidgets
  - jax
  - joblib
  - jupyterlab
  - lightgbm
  - matplotlib
  - mypy
  - nodejs
  - numba::numba
  - numpy
  - pandas-stubs
  - pandas>=2.0.0
  - pip
  - plotly
  - pre-commit
  - psutil
  - pydantic
  - pylint
  - pytest
  - pytest-cov
  - python-graphviz
  - pytorch::cpuonly
  - pytorch::pytorch
  - pytorch::torchaudio
  - pytorch::torchvision
  - pytz
  - requests
  - scikit-learn
  - scipy
  - shap
  - sqlalchemy
  - sqlalchemy-utils
  - statsmodels
  - tqdm
  - xgboost
  - yarn
  - pip:
    - aquirdturtle_collapsible_headings
    - black[jupyter]
    - corr-shap
    - cvxpy
    - isort
    - jupyter-server-proxy
    - jupyterlab-drawio
    - jupyterlab-execute-time
    - jupyterlab_vim
    - lckr-jupyterlab-variableinspector
    - mapie
    - nbqa
    - optuna
    - optuna-integration
    - pandas-datareader
    - pandas_market_calendars
    - polars
    - psycopg2
    - pynvim
    - ranger-fm
    - ruff
    - seaborn
    - tributary
