name: dev
channels:
  - defaults
dependencies:
  - python=3.11
  - dask
  - flake8
  - ipykernel
  - jax
  - joblib
  - jupyterlab
  - lightgbm
  - matplotlib
  - mypy
  - networkx
  - nodejs
  - numba::numba
  - numpy
  - pandas
  - pip
  - plotly
  - psutil
  - pylint
  - pytest
  - pytest-cov
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::cpuonly
  - pytz
  - requests
  - scipy
  - seaborn
  - shap
  - scikit-learn
  - scikit-learn-intelex
  - statsmodels
  - tqdm
  - xgboost
  - yarn
  - pip:
    - alphalens
    - aquirdturtle_collapsible_headings
    - bidask
    - black[jupyter]
    - corr-shap
    - cvxpy
    - darts
    - dask-labextension
    - empyrical
    - ipympl
    - ipywidgets
    - isort
    - jupyter-server-proxy
    - jupyterlab-drawio
    - jupyterlab-execute-time
    - jupyterlab_vim
    - lckr-jupyterlab-variableinspector
    - mlflow
    - ml_insights
    - nbqa
    - neuralforecast
    - mlforecast
    - openbb
    - optuna
    - pandas-datareader
    - pandas_market_calendars
    - pandas_ta
    - polars
    - pre-commit
    - pyfolio
    - pynvim
    - pysabr
    - pyvinecopulib
    - quantstats
    - riskfolio-lib
    - ruff
    - statsforecast
    - TA-Lib
    - web3
    - zipline-reloaded
